config/routes.rb
Rails.application.routes.draw do
  get 'books/payment_cancel'
  resources :user_profiles
  resources :charges
  resources :resources
  resources :examples
  devise_for :users
  resources :books
  root 'books#index'
end

app/models/book.rb
class Book < ActiveRecord::Base
	belongs_to :user
	belongs_to :category
	has_many :resources
	mount_uploader :my_file, FileUploader


	# can also be an IP address
	geocoded_by :address   
	# auto-fetch coordinates # would normally update everytime the model is but now only does when address is changed
	after_validation :geocode, :if => :address_changed?        
	#is_impressionable :counter_cache => true, :column_name => :page_count, :unique => :true
	is_impressionable :counter_cache => true, :column_name => :page_count, :unique => :request_hash

  #has_attached_file :book_img, styles: { book_index: "300x300>", book_show: "100x100>" }, default_url: "/images/:style/missing.png"
  #validates_attachment_content_type :book_img, content_type: /\Aimage\/.*\z/

  #validates :title, :description, :presence => true
  #alidates :title, :length => { :minimum => 6 }
  #validates :title, :uniqueness => true

 #validates :title, :description, presence: true

#validates :title, presence: true, length: { minimum: 3, maximum: 25 }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

	#impressionist actions: [:show], unique: [:session_hash]
	impressionist actions: [:show]




	#this is a 'before action', it gets ran before any of these actions are used
	#it uses the method i made (find_book) thats down the end
	#only want it to run for certain actions though
	before_action :find_book, only: [:show, :edit, :update, :destroy]

	def payment_cancel
	  @payment_cancel = "payment_cancel"
	end


	def index
		if params[:category].blank?
			@books = Book.all.order("page_count ASC")
			@books_no_order = Book.all.order(created_at: :desc).limit(10)



			#@myyy = @book.impressionist_count(:start_date=>Date.today)
			#@orgs_category_of_the_day = Book.where(["page_count > ?", 100])


		else
			@category_id = Category.find_by(name: params[:category]).id
			@books = Book.where(:category_id => @category_id).order("created_at DESC")
		end
	end 

	def show
		@book = Book.find(params[:id])
		@resources = Resource.all.map { |c| [c.tittle, c.id] }
		#@resy1 = Resource.find(params[:id]) 
		@resy2 = Resource.where(:book_id => params[:id])

		# -- get user that created current resource --
		@user = User.find(@book.user_id)

		#works too
		#@resy4 = Resource.find_by book_id: params[:id]

		#being used (gets the resources with the FK book_id the same as the current book's id PK)
		@resy5 = Resource.where(["book_id = ?", params[:id]])

		impressionist(@book)
	end

	def new
		if signed_in?
			@book = current_user.books.build
			@categories = Category.all.map { |c| [c.name, c.id] }
			@resources = Resource.all.map { |r| [r.tittle, r.id] }
		end	
	end

	def create
		@book = current_user.books.build(book_params)
		@book.category_id = params[:category_id]
		@book.my_file = params[:file]
		if @book.save
			redirect_to root_path
		else
			render 'new'
		end
	end

	def edit
		@categories = Category.all.map { |c| [c.name, c.id] }
		
	end

	def update
		@book.category_id = params[:category_id]
		if @book.update(book_params)
			redirect_to book_path(@book)
		else
			render 'edit'
		end
	end

	def destroy
		@book.destroy
		redirect_to root_path

	end

	private

		def book_params
			params.require(:book).permit(:title, :description, :author, :category_id, :my_file, :address)
		end

		def find_book
			@book = Book.find(params[:id])

			#if the view is being requested for a org thats been eithe deleted or never existed
			#redirect back to front feed
			rescue ActiveRecord::RecordNotFound
  			redirect_to root_path, :flash => { :error => 
  				"<div class='col-md-12' style='margin-left: -20px; padding-bottom: 3em;'>
					<div class='col-md-6 noOrgsError' onclick='scrollToFeed()'>
						<h2 class='col-md-11'>We cant find that Organization</h2>
						<h3 class='col-md-11'>But there are lots down there</h3>
						<h2 class='col-md-1'><span class='glyphicon glyphicon-arrow-down'></span></h2>
					</div>
				</div>"}
		end





end

app/helpers/books_helper.rb
module BooksHelper


end

app/views/books/_form.html.erb
<%= simple_form_for @book , :html => { :multipart => true } do |f| %>
<%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select a Fitting Category")%>
	
	<br><br>

	<!--			Name -->
	<h4 class="fieldHeader"> Name of the Organization </h4>
	<%= f.input :title, label: false, :input_html => { :id => 'org_name' } %>

	<!--			Description -->
	<h4 id="price" class="fieldHeader"> Description </h4>
	<%= f.input :description, label: false, :input_html => { :id => 'org_description' } %>


	<!--			Address -->
	<h4 id="address" class="fieldHeader"> Address </h4>
	<%= f.input :address, label: false, :input_html => { :id => 'org_address' } %>

	<!--			Image -->
	<h4 class="fieldHeader"> Representing image (profile picture) </h4>
	<%= f.file_field :my_file %>

	<!--			Submit -->
	<br><br>
	<%= f.button :submit %>
<% end %>

app/views/books/edit.html.erb

<!-- Instantly display image before upload-->
<script>
	$(document).ready(function(){
    var preview = $(".upload-preview img");
    
    $(".file").change(function(event){
       var input = $(event.currentTarget);
       var file = input[0].files[0];
       var reader = new FileReader();
       reader.onload = function(e){
           image_base64 = e.target.result;
           preview.attr("src", image_base64);
       };
       reader.readAsDataURL(file);
    });
});
</script>

<style>
	/* make previes image same size as old image */
	.upload-preview img {
		max-width: 480px;
		max-height: 420px;
	}
</style>


<h1>Update Organization</h1>
<ul>
<br>

<%= simple_form_for @book, :html => { :multipart => true } do |f| %>

<!--		category -->
<h4 class="fieldHeader"> Category </h4>
<%= f.select :category_id, @categories %>

	<br><br>

	<!--			Name -->
	<h4 class="fieldHeader"> Name of the Organization </h4>
	<%= f.input :title, label: false, :input_html => { :id => 'org_name' }  %>

	<!--			Description -->
	<h4 id="price" class="fieldHeader"> Description </h4>
	<%= f.input :description, label: false, :input_html => { :id => 'org_description' } %>


	<div class="col-md-6">
		<div class="col-md-6"> <h3> Old image: </h3></div> 
		<br><br>
		<hr>
		<%= image_tag @book.my_file.medium.url.to_s %><br/><br/>

	</div>
	<div class="col-md-6">
		<div class="col-md-6"> <h3> Choose new image: </h3></div> 
		<div class="col-md-6" style="margin-top: 10px; margin-left: -20px; "> <h4> <%= f.file_field :my_file, class: "file" %> </h4></div> 
		<br><br>
		<hr>
		
		<div class="upload-preview">
		    <img />
		</div>
		
	</div>

	<div class="col-md-12">
		<%= f.button :submit%>
		<%= link_to "Cancel", root_path %>
	</div>
<% end %>







app/views/books/index.html.erb

<style>
	
	.profile-index{
	
	background-color: #DFF4F5;
	color: green; 
	/*margin-left:5px;*/
	border: solid 5px white;
}

/* style for error message passed from controller
   when user tries to acces non existing record */
.noOrgsError{
	background-color: #FFC64A ;
	margin-left: -10px;
	cursor: pointer; cursor: hand; 
}
.noOrgsError h2, h3{margin-left: -10px;}
.noOrgsError span:hover{color: #DFF4F5;}
/* ./error message */




/* scrollboxes */
/* The heart of the matter */
.row {
  overflow-x: auto;
  white-space: nowrap;
}
.col-md-3 {
  display: inline-block;
  float: none;
}
/* -end  scrollboxes */

</style>

<h1 class="current-category">
	<% if params[:category]%>
 		<%= params[:category] %>
 	<% else %>
 	<h1> Feed here </h1>
 	<!-- testing purposes -->
 	<h4 class="visible-lg">large</h4>
 	<h4 class="visible-md">medium</h4>
 	<h4 class="visible-sm">small</h4>
 	<h4 class="visible-xs">x small</h4>

 	<hr>
 	<% end %>
 </h1>

<% words = %w(how wood wood would a wood chuck chuck chuck chuck chuck chuck chuck chuck chuck chuck wood) %>
<!-- counts the occourances of the words from the array 'words' -->
<% words.each_with_object(Hash.new(0)) { |word,counts| counts[word] += 1 } %>





<% if @books.count == 0 %>

	<h1> There are no Organizations to show </h1> <br><br>Ryan add in an image here<br><br>
	<hr>
	<table style="width:100%">
	  <tr>
	    <td>Okay then, </td>
	    <td><%= link_to "Bring me to the Home Page", root_path %></td>
	  </tr>
	  <tr>
	    <td></td> <!-- To create the positioning nessesary -->
	    <td>
	    <%= link_to "Bring me to my Profile (add right link in here ryan)", 
	    	user_profile_path(current_user.id) %>
	  </tr>
	</table>
<% else %>



<!-- testingggg -->
<% @books.each do |b| %>
	<!-- getting the daily view count of the current organization being looped -->
	<% @tempb = b.impressionist_count(:start_date=>Date.today) %>
	<!-- output the info if that daily count is less than 10 -->
	<% b.title if @tempb < 10 %>

<% end %><!-- end of each loop-->

<!-- end- testingggg -->
	<br><br><br><br>
			<%=  request.location.city %>
			
	<br><br><br><br>

			<% for book1 in @books.first.nearbys(10) %>
				<%= link_to book1.title, book1 %> (<%= book1.distance.round(2) %>  miles)
			<% end %>




<!-- new to Reach -->
<% if !params[:category]%>
<% if @books_no_order %>
	<div class="container testimonial-group">
		<h1 style="color: orange; margin-left: -10px;">New to Reach</h1>
		<div class="row text-center scrollBar_nice2">
			
				<% @books_no_order.shuffle.each do |book| %>

	

					<%= link_to book_path(book) do %>
						<div class="col-md-3 profile-index" style="overflow: hidden; min-height: 450px; max-height: 450px;">
							<div style="min-height: 50px; max-height: 50px; overflow: hidden;"> 
								<h4 style="font-size: 14pt">
								<%= truncate(book.title, :length => 27, :omission => '...')%>
								</h4>
							</div>
							<div style="border-bottom: 1px solid red; margin-bottom:10px; max-width: 260px; max-height: 260px; min-width: 260px; min-height: 260px;" class="test" >
								<%= image_tag book.my_file.thumb.url, class: "org_img" %>
								<br><br>
							</div>
							<div style=" max-height: 100px; min-height: 100px; overflow: hidden; white-space: normal; text-align: left;"> 
								<%=  truncate(book.description, :length => 130, :omission => '... (continued)') %>
							</div>
						</div>
					<% end %><!-- end of link-->
				
			<% end %><!-- end of loop -->
		</div>
	</div>
<% end %><!-- end of checking iv var is not empty -->
<% end %><!-- end of checking if category is being viewed -->
<!-- end- new to Reach -->

<!-- needs love -->
<% if !params[:category]%>
	<div class="container testimonial-group">
		<h1 style="color: orange;  margin-left: -10px;">Needs some Love</h1>
		<div class="row text-center scrollBar_nice2">
			<% @books.each do |book| %>
				<!-- getting the daily view count of the current organization being looped -->
				<% @tempb = book.impressionist_count(:start_date=>Date.today) %>
				<!-- output the info if that daily count is less than 10 -->
				<% if @tempb < 5 %>
					<%= link_to book_path(book) do %>
						<div class="col-md-3 profile-index" style="overflow: hidden; min-height: 450px; max-height: 450px;">
							<div style="min-height: 50px; max-height: 50px; overflow: hidden;"> 
								<h4 style="font-size: 14pt">
								<%= truncate(book.title, :length => 27, :omission => '...')%>
								</h4>
							</div>
							<div style="border-bottom: 1px solid red; margin-bottom:10px; max-width: 260px; max-height: 260px; min-width: 260px; min-height: 260px;" class="test" >
							<%= image_tag book.my_file.thumb.url, class: "org_img" %>
							<br><br>
						</div>
							<div style=" max-height: 100px; min-height: 100px; overflow: hidden; white-space: normal; text-align: left;"> 
								<%=  truncate(book.description, :length => 130, :omission => '... (continued)') %>
								<%= @tempb %>
							</div>
						</div>
					<% end %><!-- end of link-->
				<% end %><!-- end of check (checked to se if daily views is less than 5)-->
			<% end %><!-- end of loop -->
		</div>
	</div>	<!-- end- needs love -->
<% end %><!-- end of checking if category is being viewed -->

<!-- Favorites of the day -->
	<% if !params[:category]%>
	<div class="container testimonial-group">
		<h1 style="color: orange;  margin-left: -10px;">Favorites of the day</h1>
		<div class="row text-center scrollBar_nice2">
			<% @books.each do |book| %>
				<!-- getting the daily view count of the current organization being looped -->
				<% @tempb = book.impressionist_count(:start_date=>Date.today) %>
				<!-- output the info if that daily count is less than 10 -->
				<% if @tempb >= 10 %>
					<%= link_to book_path(book) do %>
						<div class="col-md-3 profile-index" style="overflow: hidden; min-height: 450px; max-height: 450px;">
							<div style="min-height: 50px; max-height: 50px; overflow: hidden;"> 
								<h4 style="font-size: 14pt">
								<%= truncate(book.title, :length => 27, :omission => '...')%>
								</h4>
							</div>
							<div style="border-bottom: 1px solid red; margin-bottom:10px; max-width: 260px; max-height: 260px; min-width: 260px; min-height: 260px;" class="test" >
							<%= image_tag book.my_file.thumb.url, class: "org_img" %>
							<br><br>
						</div>
							<div style=" max-height: 100px; min-height: 100px; overflow: hidden; white-space: normal; text-align: left;"> 
								<%=  truncate(book.description, :length => 130, :omission => '... (continued)') %>
								<%= @tempb %>
							</div>
						</div>
					<% end %><!-- end of link-->
				<% end %><!-- end of check (checked to se if daily views is less than 5)-->
			<% end %><!-- end of loop -->
		</div>
	</div>	<!-- end- needs love -->
<% end %><!-- end of checking if category is being viewed -->

<!-- end- Favorites of the day -->










<!-- ++++++++++++++++++ CATEGORY VIEW ++++++++++++++++++++ -->
	<% if params[:category]%> <!-- check if category is being viewed (in the params) -->
		<% @books.each do |book| %>
				<%= link_to book_path(book) do %>
					<div class="col-md-3 profile-index" style="overflow: hidden; min-height: 450px; max-height: 450px;">
						<div style="min-height: 50px; max-height: 50px; overflow: hidden;"> 
							<h4 style="font-size: 14pt">
							<%= truncate(book.title, :length => 27, :omission => '...')%>
							</h4>
						</div>
						<div style="border-bottom: 1px solid red; margin-bottom:10px; max-width: 260px; max-height: 260px; min-width: 260px; min-height: 260px;" class="test" >
						<%= image_tag book.my_file.thumb.url, class: "org_img" %>
						<br><br>
					</div>
						<div style=" max-height: 100px; min-height: 100px; overflow: hidden; white-space: normal; text-align: left;"> 
							<%=  truncate(book.description, :length => 130, :omission => '... (continued)') %>
							
						</div>
					</div>
				<% end %><!-- end of link-->
		<% end %><!-- end of loop -->
	<% end %><!-- end of checking if its category view -->





<!-- 	<div class="row" >
		<% @books.each do |book| %>
			<%= link_to book_path(book) do %>
				<div class="col-md-3 col-sm-6 profile-index" style="overflow: hidden;">
					<div style="min-height: 50px; max-height: 50px; overflow: hidden;"> 
						<h4 style="font-size: 14pt">
						<%= truncate(book.title, :length => 27, :omission => '...')%>
						</h4>
					</div>
					<div style="border-bottom: 1px solid red; margin-bottom:10px; max-width: 260px; max-height: 260px;" class="test" >
						<%= image_tag book.my_file.thumb.url, class: "org_img" %>
						<br><br>
					</div>
					<div style=" max-height: 100px; min-height: 100px; overflow: hidden;"> 
						<%=  truncate(book.description, :length => 130, :omission => '... (continued)') %>
					</div>
				</div>
			<% end %>
		<% end %>
	</div> end of row --> 

<% end %>



<script>
function scrollToFeed() {
	$('html, body').animate({
	    scrollTop: $(".row").offset().top
	}, 1100);

	//$('.noOrgsError').hide();

	removeTheWarning ();
}


var hasBeenThatLow = false;

function removeTheWarning (){
	$(window).scroll(function() {
	    var height = $(window).scrollTop();

	    if(height  > 250) {
	        console.log(height);
	        //$('.noOrgsError').hide();
	        hasBeenThatLow = true;
	    }

		if(height  < 10 && hasBeenThatLow == true) {
			$('.noOrgsError').css('visibility', 'hidden');
			$('.noOrgsError').hide();
			
	    }
	});
}
</script>

app/views/books/new.html.erb
<style>
.bringMeSomeWhereLinks {
  color: orange;
  font-size: 1.4em;
}
</style>

<% if signed_in? %>
  <h1> New Organization </h1>
  <br><br>
  <%=  render 'form', :book => @book %>
<% else %>
<div class="col-md-12">
  <h1>Sorry, you must be signed in to create an Organization </h1> <br>
  <h3 style="font-size: 1.7em;">Okay, bring me to: </h3> <br><br>
  <div class="col-md-2" style="margin-left: -10px;">
    <h4> <%= link_to 'Front Feed', root_path, :class => 'bringMeSomeWhereLinks' %> </h4>
    </div>
    <div class="col-md-4">
      <h4> <%= link_to "Somewhere to Log In", new_user_session_path, :class => 'bringMeSomeWhereLinks'%></h4>
    </div>
  </div>
<% end %>

<script>
function checkInput (){
   var val = $('#org_name').val();
   var val2;
  
  	//if name field has not been filled in
   if (val == null || val == ""){
   	val = "Please fill in the <text class='theme_blue'> <b>name </b></text>of the organization before telling us about it."
    } 
    //name field would have been filled in to get here
    else{
    	//temporally store text within name field in here
   		val2 = val;
   		//construct the string witht the correct values
   		val = "Tell us about " + "<b class='theme_blue'>" + val2 + "</b>" + " (Description).";
    }

    //output result to screen
   document.getElementById("price").innerHTML = val;
}

$( document ).ready(function() {
    $('#org_description').focus(function() 
    { 
    	//alert('999'); 
    	checkInput();
    });
});	


</script>

app/views/books/payment_cancel.html.erb
<h1> you successfully cancelled, you did not purchase the resource </h1>

app/views/books/show.html.erb


<%= link_to root_path, style: "color: red;" do %>
    <span id="back-arrow" style="font-size: 3em; margin-top: -30px;" class="glyphicon glyphicon-circle-arrow-left"></span>
<% end %>

<div class="row">
	<!--<h2> <%= @book.author %></h2>-->
	<div class="col-md-4 minus_10">
		<div class="col-md-12">
			<%= image_tag @book.my_file.medium.url, :class => "resource-img3ryannnnn" %>
		</div>
		<div class="col-md-12 minus_15" ><br>	
			<text class="col-md-12" ><b>Organization Details</b></text>
			<table class="col-md-12">
			  <tr>
			    <td class="col-md-5 " >Organizer: </td>
			    <td class="col-md-7" ><a href="mailto:"><%= @user.email %></a></td>
			  </tr>
			  <tr>
			    <td class="col-md-5 " >Total Views: </td>
			    <td class="col-md-7" ><%= "#{@book.impressionist_count}" %></td>
			  </tr>
			  <tr>
			    <td class="col-md-5" >Views Today: </td>
			    <td class="col-md-7" ><%= "#{@book.impressionist_count(:start_date=>Date.today)}" %></td>
			  </tr>
			  <tr>
			    <td class="col-md-5" >Joined Reach: </td>
			    <td class="col-md-7" ><%= (@book.created_at).strftime("%B") %> <%= @book.created_at.strftime("%y") %>'</td>
			  </tr>	
			</table>

			<% for book in @book.nearbys(10) %>
				<%= link_to book.address, book %> (<%= book.distance.round(2) %>  miles )
			<% end %>

			<!-- Tools for the org creator (when signed in)-->
			<div class="col-md-12" >
				<% if user_signed_in? %>
					<% if @book.user_id == current_user.id %>
						<%= link_to "Edit", edit_book_path(@book),  class: "btn btn-info editOrgBtn" %>
						<%= link_to "Delete", book_path(@book), 
							method: :delete, 
							data: { confirm: "Are you sure you want to delete this book?"}, 
							class: "btn btn-danger deleteOrgBtn" 
						%>
					<% end %>
				<% end %>
			</div>
		</div>
	</div>
	<div class="col-md-8">
		<p> 
			<text style="font-size: 2.4em;"> <%= @book.title %> - </text>
		 	<text style="font-size: 1.4em;"> <%= @book.category.name %></text>
		</p>
		<h2> <%= @book.description %></h2>

		<style>
			.resource-img{
				width:100%;
				height:100%;
			}
			.minus_10{ margin-left: -10px }
			.minus_15{ margin-left: -15px }
			.minus_20{ margin-left: -20px }
		</style>

		<!-- Resourcess -->
		<h2 style="margin-top: 100px;"> Requested Resources (<%= @resy5.count %>/3)</h2>
		<!-- If there are resources -->
		<% if @resy5.present? %>
			<% @resy5.each do |r| %>
			<%= link_to resource_path(r) do %>
			    <div class="col-lg-4 col-sm-4 minus_10">
			      	<div class="circle-tile ">
						<div class="circle-tile-heading dark-blue" style="overflow: hidden;">
							<%= image_tag r.image_file.url, :class => "resource-img" %>
						</div>
				        <div class="circle-tile-content dark-blue">
					        <text style="color: white;">
					        	<%= truncate(r.tittle, :length => 27, :omission => '...') %>
					        </text><br><br>
					        <div class="text-faded" style="min-height: 60px; 
					        							   max-height: 60px; overflow: hidden;">
					        	<%= truncate(r.reason, :length => 84, :omission => '...') %> 
					        </div><br> 
					        <div class="circle-tile-footer circle-tile-number" style="bottom:0;">
					        	More Info | Buy <i class="fa fa-chevron-circle-right"></i>
					        </div>
				        </div>
			      </div>
			    </div>
			<% end %>
		<% end %>
		<!-- If there are NOT any resources -->
		<% elsif @resy5.present? == false && user_signed_in? && @book.user_id == current_user.id %>
			<%= link_to new_resource_path(:tittleP => @book.id) do %>
			    <div class="col-lg-4 col-sm-4 minus_10">
			      	<div class="circle-tile ">
						<div class="circle-tile-heading dark-blue" style="">
							<i class="glyphicon glyphicon-plus" style="font-size: 40px; margin-top:22%; margin-left:2%;" ></i>
						</div>
						<div class="circle-tile-content dark-blue">
							<div style="color: grey;"> Add 
								<text style="color: white;"> 
									<span style="padding-right: 3px; padding-left: 3px;"> First </span> 
								</text>  
								resource for 
							</div><br>
						 	<div class="text-faded" style="color: orange; min-height: 60px; max-height: 60px; overflow: hidden;"><%= @book.title %>
						 	</div><br>
							<div class="circle-tile-footer circle-tile-number" href="#">Create New <i class="fa fa-chevron-circle-right"></i></div>
						</div>
			        </div>
			    </div>
			<% end %>
		<% end %>
		<!-- If there are resources BUT there is less than 3 -->
		<% if @resy5.count > 0 && @resy5.count < 3 && user_signed_in? && @book.user_id == current_user.id %>
			<%= link_to new_resource_path(:tittleP => @book.id) do %>
			    <div class="col-lg-4 col-sm-4">
			      	<div class="circle-tile ">
						<div class="circle-tile-heading dark-blue" style="">
							<i class="glyphicon glyphicon-plus" style="font-size: 40px; margin-top:22%; margin-left:2%;" ></i>
						</div>
						<div class="circle-tile-content dark-blue">
							<div style="color: grey;"> Add 
								<text style="color: white;"> 
									<span style="padding-right: 3px; padding-left: 3px;"> New </span>
								</text> resource for  
							</div><br>
						 	<div class="text-faded" style="color: orange; min-height: 60px; 
						 								   max-height: 60px; overflow: hidden;">
						 		<%= @book.title %>
						 	</div> <br>
							<div class="circle-tile-footer circle-tile-number" href="#">Create New 
								 <i class="fa fa-chevron-circle-right"></i>
							</div>
						</div>
			        </div>
			    </div>
			<% end %>
		<% end %>
	</div><!-- ./ col-md-8 -->
	<!-- </div> -->
</div> <!-- end of row -->





app/views/books/view_all_books.erb
	<!-- If there are resources -->
	<% if @resy5.present? %>
		<% @resy5.each do |r| %>
		    <div class="col-lg-4 col-sm-4">
		      <div class="circle-tile ">
		        <a href="#"><div class="circle-tile-heading dark-blue"><i class="fa fa-users fa-fw fa-3x"></i></div></a>
		        <div class="circle-tile-content dark-blue">
			          <%= link_to truncate(r.tittle, :length => 27, :omission => '...') , 
								resource_path(r), class: "circle-tile-description text-faded" %><br>
		          <div class="text-faded "><%= r.reason %> </div> <br>

		          <a class="circle-tile-footer circle-tile-number" href="#">More Info | Buy <i class="fa fa-chevron-circle-right"></i></a>
		        </div>
		      </div>
		    </div>
		<% end %>