config/routes.rb
Rails.application.routes.draw do
  get 'books/payment_cancel'
  resources :user_profiles
  resources :charges
  resources :resources
  resources :examples
  devise_for :users
  resources :books
  root 'books#index'
end

app/views/resources/_form.html.erb
<%= simple_form_for @resource, :html => { :multipart => true } do |f| %>
  <%= f.error_notification %>

<style> #temp_field{ display: none; } </style>
<script>
	//put vposted value fom hidden field into dropdown if its posted sucesfully (not blank)
	if ($('#temp_field').val() != '' && $('#temp_field').val() != null ) {
	     $('#book_id').val($('#temp_field').val()); 
	}
</script>

  <div class="form-inputs">
  	<!--			Image -->
	<h4 class="fieldHeader"> Image of resourse</h4>
	<%= f.file_field :image_file %>
    <%= f.input :tittle %>
    <%= f.input :reason %>
    <%= f.input :price %>
    <%= f.input :temp_field , :input_html => { :id => 'temp_field' }, label: false %>
    <%= select_tag(:book_id, options_for_select(@books))%>
    
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/resources/edit.html.erb
<h1>Editing Resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Resources</h1>

<table>
  <thead>
    <tr>
      <th>Tittle</th>
      <th>Reason</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resources.each do |resource| %>
      <tr>
        <td><%= resource.tittle %></td>
        <td><%= resource.reason %></td>
        <td><%= resource.price %></td>
        <td><%= link_to 'Show', resource %></td>
        <td><%= link_to 'Edit', edit_resource_path(resource) %></td>
        <td><%= link_to 'Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resource', new_resource_path %>

app/views/resources/new.html.erb
<h1 id="newResourcTitle">New Resource </h1>

<%= render 'form' %>

<%= link_to 'Back', resources_path %>

<script>

	$(document).ready(function(){
		var postedVal = $('#book_id').find("option:selected").text();
	    document.getElementById("newResourcTitle").innerHTML = "New Resource for " + postedVal;
	});

	$("#book_id").change(function() {
	var currentSelectedVal = $(this).find("option:selected").text();
    
    //document.write("Hello World!");
    document.getElementById("newResourcTitle").innerHTML = "New Resource for " + currentSelectedVal;
});
</script>