config/routes.rb
Rails.application.routes.draw do
  get 'books/payment_cancel'
  resources :user_profiles
  resources :charges
  resources :resources
  resources :examples
  devise_for :users
  resources :books
  root 'books#index'
end

app/models/example.rb
class Example < ActiveRecord::Base
	mount_uploader :my_file, FileUploader
end

app/controllers/examples_controller.rb
class ExamplesController < ApplicationController
  before_action :set_example, only: [:show, :edit, :update, :destroy]

  # GET /examples
  # GET /examples.json
  def index
    @examples = Example.all
  end

  # GET /examples/1
  # GET /examples/1.json
  def show
  end

  # GET /examples/new
  def new
    @example = Example.new
  end

  # GET /examples/1/edit
  def edit
  end

  # POST /examples
  # POST /examples.json
  def create
    @example = Example.new(example_params)
    @example.my_file = params[:file]
    respond_to do |format|
      if @example.save
        format.html { redirect_to @example, notice: 'Example was successfully created.' }
        format.json { render :show, status: :created, location: @example }
      else
        format.html { render :new }
        format.json { render json: @example.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /examples/1
  # PATCH/PUT /examples/1.json
  def update
    respond_to do |format|
      if @example.update(example_params)
        format.html { redirect_to @example, notice: 'Example was successfully updated.' }
        format.json { render :show, status: :ok, location: @example }
      else
        format.html { render :edit }
        format.json { render json: @example.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /examples/1
  # DELETE /examples/1.json
  def destroy
    @example.destroy
    respond_to do |format|
      format.html { redirect_to examples_url, notice: 'Example was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_example
      @example = Example.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def example_params
      params.require(:example).permit(:my_file)
    end
end

app/helpers/examples_helper.rb
module ExamplesHelper
end

app/views/examples/_form.html.erb
<%= simple_form_for(@example) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.file_field :my_file %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/examples/edit.html.erb
<h1>Editing Example</h1>

<%= render 'form' %>

<%= link_to 'Show', @example %> |
<%= link_to 'Back', examples_path %>

app/views/examples/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Examples</h1>

<table>
  <thead>
    <tr>
      <th>My file</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @examples.each do |example| %>
      <tr>
        <td>
          <a href = "<%= example.my_file %>" > 
            <img src= "<%= example.my_file %>" />
          </a> 
        </td>
        <td><%= link_to 'Show', example %></td>
        <td><%= link_to 'Edit', edit_example_path(example) %></td>
        <td><%= link_to 'Destroy', example, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Example', new_example_path %>

app/views/examples/new.html.erb
<h1>New Example</h1>

<%= render 'form' %>

<%= link_to 'Back', examples_path %>

app/views/examples/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>My file:</strong>
  <%= @example.my_file %>
</p>

<%= link_to 'Edit', edit_example_path(@example) %> |
<%= link_to 'Back', examples_path %>